### PR TITLE
Define a release process type in Procfile.

### PR DESCRIPTION
**Pull request by jumpyoshim**
FYI: https://devcenter.heroku.com/articles/release-phase#specifying-release-phase-tasks

### CODE REVIEW

**Comment by jumpyoshim** [comment]
review me, plz.

**Comment by jumpyoshim** [comment]
Please review.

**Comment by CaseyFaist** [comment]
Thanks for the contribution! Since this repo is a starter guide, and a companion to the Getting Started article on Heroku, we only need the Procfile commands specified here: https://devcenter.heroku.com/articles/getting-started-with-python#define-a-procfile

**Comment by jumpyoshim** [comment]
@CaseyFaist   
Thank you for reviewing this pull request!
I tried to access the  Getting Started article on Heroku. It was written:

>The Procfile in the example app you deployed looks like this:
> ```
> release: python manage.py migrate
> web: gunicorn gettingstarted.wsgi --log-file -
> ```

I think that this pull request is as documented.

**Pull request closed without merging**
